# Inhoud van de vitaliteitsmeter voor organisaties. Wordt gebruikt voor het voorstel en later voor de pagina.
SCHAAL = ['Helemaal niet', 'Nauwelijks', 'Deels', 'Grotendeels', 'Helemaal']
THEMAS = [
 dict(id='inzicht', naam='Inzicht en cijfers', vraag='Weet je waar je staat?', basis='Bouwblok scope, relevantie en kwaliteit. De businesscase.',
  stellingen=['We weten hoeveel verzuim onze organisatie per jaar kost.',
              'We weten in welke teams of functies het verzuim zit en wat de oorzaken zijn.',
              'We meten minstens één keer per jaar hoe medewerkers hun werkdruk en werkplezier ervaren.',
              'De directie bespreekt minstens twee keer per jaar de cijfers over verzuim en vitaliteit.'],
  laag='Je stuurt nu vooral op gevoel. Zonder cijfers is het lastig om budget en steun te krijgen.',
  midden='Er zijn cijfers maar ze sturen nog niet. De volgende stap is ze vast op de agenda zetten.',
  hoog='Je weet waar je staat en wat het kost. Dat is een goede basis om op te sturen.',
  stappen=['Bereken wat verzuim nu kost met de verzuimrekentool.', 'Zoek uit in welke teams en functies het verzuim zit.', 'Spreek af welke cijfers de directie elk half jaar ziet.'],
  links=[('Verzuimrekentool', 'tools#rekentool-kop'), ('Artikel: Businesscase vitaliteit', 'artikelen/businesscase-vitaliteit-maken'), ('Whitepaper: De businesscase voor vitaliteit', 'whitepaper-businesscase-vitaliteit')]),
 dict(id='werkdruk', naam='Werkdruk en herstel', vraag='Is het werk te doen?', basis='JD-R-model: stressbronnen en herstel.',
  stellingen=['Werkdruk is een vast onderwerp in het teamoverleg.',
              'Medewerkers kunnen hun werk doen in de tijd die ervoor staat.',
              'Bij te hoge werkdruk stellen we prioriteiten en schrappen we werk.',
              'Er is ruimte voor pauzes en herstel tijdens en na het werk.'],
  laag='Werkdruk krijgt nu weinig aandacht. Dat is een risico voor verzuim en verloop.',
  midden='Werkdruk is bespreekbaar. Het leidt nog niet altijd tot keuzes in het werk.',
  hoog='Werkdruk is bespreekbaar en jullie grijpen in als het te veel wordt.',
  stappen=['Zet werkdruk op de agenda van elk teamoverleg.', 'Maak samen een lijst van werk dat kan stoppen.', 'Spreek af wat je doet als het te veel wordt.'],
  links=[('Artikel: Moet je je druk maken over werkdruk?', 'artikelen/moet-je-je-druk-maken-over-werkdruk'), ('Whitepaper: Werkdruk verlagen', 'whitepaper-werkdruk-verlagen'), ('Training Werkdruk verlagen', 'trainingen#werkdruk')]),
 dict(id='energie', naam='Energie en werkplezier', vraag='Geeft het werk energie?', basis='JD-R-model: energiebronnen. Het ABC van autonomie, binding en competentie.',
  stellingen=['Medewerkers hebben invloed op hoe zij hun werk doen.',
              'Collega\'s steunen elkaar en voelen zich verbonden met hun team.',
              'Medewerkers doen werk dat past bij hun kwaliteiten en kunnen zich ontwikkelen.',
              'Medewerkers krijgen waardering voor wat zij doen.'],
  laag='Het werk geeft nu weinig energie terug. Dan weegt werkdruk zwaarder.',
  midden='Er zijn energiebronnen. Ze zijn nog niet voor iedereen vanzelfsprekend.',
  hoog='Medewerkers halen energie uit hun werk. Dat beschermt tegen uitval.',
  stappen=['Vraag in elk team wat energie geeft en wat energie kost.', 'Geef medewerkers meer zeggenschap over hoe zij hun werk doen.', 'Maak ontwikkeling een vast onderwerp in gesprekken.'],
  links=[('Artikel: Bevlogenheid is geen luxe', 'artikelen/bevlogenheid-is-geen-luxe'), ('Het JD-R-model', 'tools#jdr-model'), ('Training Verminder stress, verhoog bevlogenheid', 'trainingen#bevlogenheid')]),
 dict(id='leiderschap', naam='Leiderschap', vraag='Geven leidinggevenden het voorbeeld?', basis='Bouwblok leiderschap op alle niveaus.',
  stellingen=['Directie en leidinggevenden geven zelf het goede voorbeeld bij vitaliteit.',
              'Leidinggevenden herkennen signalen van overbelasting bij hun medewerkers.',
              'Leidinggevenden voeren op tijd het gesprek over werkdruk en vitaliteit.',
              'Leidinggevenden krijgen training en ondersteuning om dat goed te doen.'],
  laag='Leidinggevenden zijn nog niet toegerust. Daardoor komen signalen laat op tafel.',
  midden='Leidinggevenden zien het belang. Niet iedereen heeft de vaardigheden om het gesprek te voeren.',
  hoog='Leidinggevenden geven het voorbeeld en voeren het gesprek op tijd.',
  stappen=['Bespreek in het managementteam welk voorbeeld jullie geven.', 'Train leidinggevenden in signalen herkennen en het gesprek voeren.', 'Maak vitaliteit een vast onderwerp in het overleg van leidinggevenden.'],
  links=[('Artikel: Burn-out voorkomen in je team', 'artikelen/burn-out-voorkomen-in-je-team'), ('Whitepaper: Burn-out signaleren', 'whitepaper-burn-out-signaleren'), ('Coaching voor leidinggevenden', 'diensten#coaching')]),
 dict(id='beleid', naam='Beleid en organisatie', vraag='Heeft vitaliteit een vaste plek?', basis='Bouwblok identiteit en cultuur. Verankeren volgens Kotter.',
  stellingen=['We hebben gezondheids- of vitaliteitsbeleid opgesteld.',
              'Dat beleid heeft doelen die passen bij onze organisatie.',
              'Eén persoon is verantwoordelijk voor vitaliteit en heeft daar tijd en mandaat voor.',
              'Vitaliteit heeft een vast budget.',
              'Vitaliteit is een vast onderdeel van de planning en van de gesprekken met medewerkers.'],
  laag='Vitaliteit hangt nu af van losse initiatieven en van wie er tijd voor heeft.',
  midden='Er is beleid of een eigenaar. Doelen, budget en planning zijn nog niet allemaal geregeld.',
  hoog='Vitaliteit heeft een eigenaar, doelen en budget. Het hoort bij de bedrijfsvoering.',
  stappen=['Wijs één eigenaar aan met tijd en mandaat.', 'Leg twee of drie meetbare doelen vast.', 'Geef vitaliteit een vaste plek in de begroting en de planning.'],
  links=[('Artikel: Vitaliteitsbeleid opzetten', 'artikelen/vitaliteitsbeleid-opzetten-stappenplan'), ('Whitepaper: Vitaliteitsbeleid opzetten', 'whitepaper-vitaliteitsbeleid-opzetten'), ('Strategisch advies', 'diensten#strategisch-advies')]),
 dict(id='gedrag', naam='Gezond gedrag en omgeving', vraag='Is gezond kiezen makkelijk?', basis='Bouwblokken toegankelijkheid, kwaliteit en communicatie.',
  stellingen=['Medewerkers weten welk vitaliteitsaanbod er is en krijgen tijd om mee te doen.',
              'De werkomgeving maakt gezond gedrag makkelijk. Denk aan gezond eten en ruimte om te bewegen.',
              'We kiezen maatregelen die wetenschappelijk onderbouwd zijn.',
              'We communiceren regelmatig over vitaliteit en delen ervaringen van collega\'s.'],
  laag='Er is weinig aanbod of medewerkers weten het niet te vinden.',
  midden='Er is aanbod. Het bereikt nog niet de mensen die het nodig hebben.',
  hoog='Het aanbod is bekend en onderbouwd en de omgeving helpt mee.',
  stappen=['Zet het aanbod op één plek en vertel er vaak over.', 'Geef medewerkers tijd om mee te doen.', 'Kies maatregelen die onderbouwd zijn en meet wat ze opleveren.'],
  links=[('Artikel: Zes bouwblokken voor vitaliteitsbeleid', 'artikelen/zes-bouwblokken-vitaliteitsbeleid'), ('Inspiratiesessies', 'trainingen#workshops'), ('Vitaliteitskalender', 'kalender')]),
]
NIVEAUS = [(0, 'Hier ligt werk'), (40, 'In ontwikkeling'), (70, 'Staat stevig')]
TOTAAL = {'laag': 'Vitaliteit hangt nu af van losse initiatieven. Er is veel te winnen.',
          'midden': 'Er gebeurt al het nodige. De samenhang kan beter.',
          'hoog': 'Vitaliteit heeft een vaste plek. Kijk waar je nog kunt aanscherpen.'}
for t in THEMAS:
    assert len(t['stellingen']) in (4, 5) and len(t['stappen']) == 3
    for s in t['stellingen'] + t['stappen'] + [t['laag'], t['midden'], t['hoog']]:
        assert '—' not in s and '–' not in s
AANTAL = sum(len(t['stellingen']) for t in THEMAS)
